logging:
  level: INFO
  loggers:
    de.egladil.winkel: DEBUG

server:
  applicationConnectors:
  - type: http 
    port: 8880
  adminConnectors:
  - type: http
    port: 8881

    # Database settings.
database:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: energy
    # the password
    password: energy
    # the JDBC URL; the database is called hello_world
    url: jdbc:mysql://localhost:3306/energy_raw
    # the SQL query to run when validating a connection's liveness
    validationQuery: "/* MyService Health Check */ SELECT 1"
    